### ISSUE TITLE
Takes around 6+ seconds to load bg_top@2x.png static asset, over fast connections

### ISSUE THREAD

**Issue by stephendonner** [mozilla/games.mozilla.org#119]
Consistently, the non-cached (client-side) load of games.mozilla.org takes longer than it should to load, primarily due to one static asset: https://games.mozilla.org/assets/img/bg_top@2x.png

It typically takes 6+ seconds to load that, even over a fast connection:

https://www.webpagetest.org/result/170117_JC_2Y3/

**Comment by cvan** [comment]
Thanks for filing. These graphics were included during the redesign, which was handled by Andre and some external contractors.

This is indeed a hefty asset.

1. Because these images are included using `<img>` (instead of with `background-image` in CSS), both the smaller version and the `2x` version are *always* downloaded, despite the media queries to toggle the `2x` version:
```html
        <img class="headline headline-desktop" src="assets/img/headline@2x.png" alt="The Future of Web Games">
        <img class="headline headline-mobile" src="assets/img/headline_mobile.png" alt="The Future of Web Games">
```

2. It can be compressed some more with `pngquant`.
3. But, for what it's worth, I'm not sure that this background image is really necessary. At least the Firefox Nightly-esque shape could be recreated in vectors with a relatively SVG. The sky, if actually still necessary, could be included as a much smaller and separate JPEG.
