### ISSUE TITLE
contributing to mozilla games and overall webvr as a sound designer

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [mozilla/games.mozilla.org#157]
# **Greetings**

---

**I would like to:**
- *contribute to Mozilla WebVR as a sound designer:*
- *contribute to Mozilla overall game development as a sound designer:*

---

**you can** 
- *check my github portfolio (usually contribute with minor issues documentation and so on so forth*
- *check my vimeo page to get an idea of my level of skills: https://vimeo.com/tiagomoraismorgado*

---

**I would also recommend you guys to check:**

https://vimeo.com/223772477
https://vimeo.com/223772453
https://vimeo.com/223772408

**Comment by cvan** [comment]
First off, nice work! Really like the feel of them - and your Bandcamp.

Feel free to join us on the [WebVR Slack](https://webvr.rocks/chat) and [A-Frame Slack](https://slacknow.herokuapp.com/aframevr)! There are lots of folks in the community who are looking to pair up with sound engineers/artists and create some compelling content. Reach me on the Slacks, if you're interested. I'll close this issue, since I think I've answered your question. Let me know if I can be of any more help. Thanks!
